apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -small-wss

bases:
- ../base

commonLabels:
  app: memcached-mutilate-small-wss

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - threads=6
  - load_records=17575000  # 17.5M
  - records=17575000       # 17.5M
  - value=1000             # ( keys 30B + value 1000B ) * 17.5M <= 20G
  - qps=140000            # MAX QPS. For max number workloads (8 small): 140000.  For single instance: 200000.

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: service
            resources:
              requests:
                cpu: 2
                memory: 22G
              limits:
                cpu: 2
                memory: 22G
          - name: generator
            resources:
              requests:
                cpu: 6
                memory: 1G
              limits:
                cpu: 6
                memory: 1G
