# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Single staged Dockerfile to build wca as pex file that includes 
# confluent kafka python library build from sources.
FROM centos:7

RUN echo "" && rpm --import https://packages.confluent.io/rpm/5.2/archive.key
COPY /configs/confluent_repo/confluent.repo /etc/yum.repos.d/confluent.repo

RUN yum -y update && yum -y install epel-release
RUN yum -y install python36 python-pip which make git \
        librdkafka1 librdkafka-devel gcc python3-devel
RUN pip install pipenv

WORKDIR /wca

COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock
RUN pipenv install --dev --deploy

RUN git clone https://github.com/confluentinc/confluent-kafka-python
RUN cd confluent-kafka-python && git checkout v1.0.1

# Cache will be propably invalidated here.
COPY . .

RUN git clean -fdx
ENV OPTIONAL_FEATURES=kafka_storage
RUN make wca_package
