kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    name: cadvisor
spec:
  selector:
    name: cadvisor
  ports:
    - name: cadvisor
      port: 9101
      targetPort: 9101
---
kind: Service
apiVersion: v1
metadata:
  name: kube-state-metrics
  namespace: cadvisor
  labels:
    name: kube-state-metrics
spec:
  selector:
    name: cadvisor
  ports:
    - name: kube-state-metrics
      port: 8080
      targetPort: 8080