# Full example for Mesos with anomalies stored in Kafka.

runner: !DetectionRunner
  measurement_runner: !MeasurementRunner
    node: !MesosNode
      mesos_agent_endpoint: 'http://127.0.0.1:5051'
      timeout: 5
      ssl: !SSL
        server_verify: True

    interval: 1.

    metrics_storage: !LogStorage
      output_filename: '/tmp/output_anomalies.log'

    # Decorate every metric with extra labels.
    extra_labels:
      env_id: "$HOST_IP"

  # Example use of external component.
  # Requires registration with -r example.external_package:ExampleDetector
  detector: !ExampleDetector
