{
 "title": "2LM contention demo",
 "tags": [ "2lm" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "SLI normalized (lower is better)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "avg(apm__sli_normalized)", "legendFormat": "SLI" },
    { "expr": "sum(wca_tasks)", "legendFormat": "Pods" },
    { "expr": "1", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(wca_tasks)", "legendFormat": "tasks" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 5 },
   "content": "## **node11**, **node12**: *Optande DC PMEM based nodes* - 1TB 2LM Memory Mode with 1/4 and 1/5 ratios , \n## **node13**, **node14**: *DRAM only nodes* - 300/400 GB of RAM\n"
  },
  {
   "title": "App cache contention sensitivity = (Intenstiy * Utili) / RW",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scaled__app_contention_sensitivity",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Node contention risk (average)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 8 },
   "targets": [
    { "expr": "scaled__node_contention_risk", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Node BW  (current)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(platform__pmm_total_mb_per_second) by (node) / 1e3",
     "legendFormat": "{{node}} | NVM"
    },
    {
     "expr": "sum(platform__dram_total_mb_per_second) by (node) / 1e3",
     "legendFormat": "{{node}} | RAM"
    },
    { "expr": "sum(node__bw) by (node) / 1e3", "legendFormat": "{{node}} | TOTAL" },
    { "expr": "sum(node__dram_hit) by (node)", "legendFormat": "{{node}} | HITRATIO" },
    {
     "expr": "sum(platform__dimm_total_size_bytes{type=\"ram\"} / 1e6) by (node)",
     "legendFormat": "{{node}} | RAM size (MB)"
    },
    {
     "expr": "sum(platform__memory_mode_size_bytes / 1e6) by (node)",
     "legendFormat": "{{node}} | NVM size in 2LM (MB)"
    },
    {
     "expr": "platform__dimm_total_size_bytes{type=\"ram\"} / on (host) platform__memory_mode_size_bytes",
     "legendFormat": "{{host}} | RAM/NVM Ratio"
    }
   ]
  },
  {
   "title": "Workloads memory profile  (average)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 16 },
   "targets": [
    { "expr": "app__cpus_usage", "legendFormat": "{{app}} | CPU" },
    { "expr": "app__wss", "legendFormat": "{{app}} | WSS (GB)" },
    { "expr": "app__rss", "legendFormat": "{{app}} | RSS (GB)" },
    { "expr": "app__bw", "legendFormat": "{{app}} | BW (GB/s)" },
    { "expr": "app__rw", "legendFormat": "{{app}} | RW %" },
    {
     "expr": "app__memory_intensity",
     "legendFormat": "{{app}} | Intensity (GB/s  per cpu)"
    },
    { "expr": "app__memory_utilization", "legendFormat": "{{app}} | Utilization %" },
    {
     "expr": "app__contention_sensitivity",
     "legendFormat": "{{app}} | Contention  sensitivity"
    }
   ]
  },
  {
   "title": "Apps per node (current)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 16 },
   "targets": [
    { "expr": "appnode__count", "legendFormat": "{{app}} | {{node}}" }
   ]
  },
  {
   "title": "App contention risk on node (used for Filter/Predicates)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "app__contention_risk_on_node", "legendFormat": "{{app}} | {{node}}" }
   ]
  },
  {
   "title": "Fit (used for Priorities)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "repeat": "app",
   "targets": [
    { "expr": "fit_without_risk", "legendFormat": "{{app}} | {{node}}" }
   ]
  },
  {
   "title": "Workloads collocation effect (average)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg(apm__sli_normalized) by (app)",
     "legendFormat": "{{app}} | SLI/SLO"
    },
    {
     "expr": "avg(apm__sli_normalized{mode=\"1lm\"}) by (app)",
     "legendFormat": "{{app}} | SLI/SLO [1lm]"
    },
    {
     "expr": "avg(apm__sli_normalized{mode=\"2lm\"}) by (app)",
     "legendFormat": "{{app}} | SLI/SLO [2lm]"
    },
    {
     "expr": "(avg(apm__sli_normalized{mode=\"2lm\"}) by (app)) - (avg(apm__sli_normalized{mode=\"1lm\"}) by (app))",
     "legendFormat": "{{app}} | 2LM impact"
    }
   ]
  },
  {
   "title": "Tasks (pods) by app (Current)",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 43 },
   "targets": [
    { "expr": "app__count", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Tasks (pods) by node (current)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
   "targets": [
    { "expr": "wca_tasks", "legendFormat": "{{node}}" }
   ]
  }
 ]
}