apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -coldstart

resources:
- ../small
- ../small-wss
- ../big-wss
- ../big
- ../medium-wss
- ../medium

commonAnnotations:
  cri-resource-manager.intel.com/cold-start: |
    service: {duration: 120s}
    generator: {duration: 120s}

