apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    k8s-app: Prometheus
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: prometheus
spec:
  type: NodePort
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    prometheus: prometheus
