# Full example for Kubernetes running as daemonset (in-cluster k8s config)
# Requires environment variables:
# - KUBERNETES_SERVICE_HOST - provided by default by Kuberenetes
# - KUBERNETES_SERVICE_PORT - provided by default by Kubernetes
# - HOST_IP - need to explicitly enabled in Pod spec using downward-api
# - HOSTNAME - default provided by OS

runner: !MeasurementRunner
  interval: 5.0
  node: !KubernetesNode
    cgroup_driver: cgroupfs
    monitored_namespaces: ["default"]
    kubeapi_host: !Env KUBERNETES_SERVICE_HOST
    kubeapi_port: !Env KUBERNETES_SERVICE_PORT
    node_ip: !Env HOST_IP


  metrics_storage: !LogStorage
    overwrite: True
    output_filename: /var/lib/wca/metrics.prom

  extra_labels:
    node: !Env HOSTNAME
  event_names:
    - task_cycles # do not remove: USED BY E2E tests
    - task_instructions
  enable_derived_metrics: True

  wss_reset_interval: 1
