apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- small
- small-wss
- medium
- medium-wss
- big
- big-wss
- _hmem

commonLabels:
  workload: memcached-mutilate
  domain: test

images:
- name: mutilate
  newName: 100.64.176.12:80/wca/mutilate
  newTag: master

commonAnnotations:
  topologyhints.cri-resource-manager.intel.com/pod: "false"

  # TOGETHER
  cri-resource-manager.intel.com/affinity: |
    generator: [ service ]
    service: [ generator ]

  # SEPARATE
  # cri-resource-manager.intel.com/anti-affinity: |
  #   service: [ generator ]
  #   generator: [ service ]
