apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -medium-wss

resources:
- ../base

commonLabels:
  app: memcached-mutilate-medium-wss

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - threads=6
  - load_records=35150000 # 35.1M
  - records=35150000      # 35.1M
  - value=1000            # ( keys 30B + value 1000B ) * 35.1M <= 40GB
  - qps=140000            # MAX QPS. For max number workloads (8 small): 140000.  For single instance: 200000.

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: service
            resources:
              requests:
                cpu: 2
                memory: 45G
              limits:
                cpu: 2
                memory: 45G
          - name: generator
            resources:
              requests:
                cpu: 6
                memory: 1G
              limits:
                cpu: 6
                memory: 1G
